name: test

services:
  loki:
    build: 
      context: ./
      dockerfile: ./tests/loki/Dockerfile
    volumes:
      - ./tests/loki/config.yml:/etc/loki/config.yml:ro

  promtail:
    image: grafana/promtail:2.8.2
    user: ${_UID}:${_GID}
    volumes:
      - ./tests/promtail/config.yml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tests/series_curl/input_log:/var/log
    command:
      - --config.file=/etc/promtail/config.yaml

  flog:
    image: mingrammer/flog:0.4.3
    user: ${_UID}:${_GID}
    command:
      - --loop
      - --format=json
      - --number=1 
      - --delay=1s
      - --type=log
      - --output=/var/log/flog.log
      - --overwrite         
    volumes:
      - ./tests/series_curl/input_log:/var/log

  series_curl:
    build: ./tests/series_curl
    user: ${_UID}:${_GID}
    volumes:
      - ./tests/series_curl:/tests/series_curl
    init: true

networks:
  test_network:
  default:
    name: test_network